### ISSUE TITLE
Adding some missing systems 

### ISSUE THREAD

**Issue by getupor** [GeekRhapsody/es-theme-tiled#1]
Hello
Could it be possible to add some systems that are missing in RetroBat ?
(link to Carbon logos as exemple)

**Zinc**
```
    <name>zinc</name>
    <fullname>Zinc</fullname>
    <path>~\..\roms\zinc</path>
    <manufacturer>Arcade</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/zinc.png](url)

**Wasm-4**    
```
    <name>wasm4</name>
    <fullname>WASM-4</fullname>
    <path>~\..\roms\wasm4</path>
    <manufacturer>Fantasy Console</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/wasm4.svg](url)

**Namco2x6**
```
    <name>namco2x6</name>
    <fullname>Namco 2x6</fullname>
    <path>~\..\roms\namco2x6</path>
    <manufacturer>Namco</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/namco2x6.svg](url)

**Pinball FX2**
```
    <name>pinballfx2</name>
    <fullname>Pinball FX2</fullname>
    <path>~\..\roms\pinballfx2</path>
    <manufacturer>Pinball</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/pinballfx2.png](url)

**Zaccaria Pinball**
```
    <name>zaccariapinball</name>
    <fullname>Zaccaria Pinball</fullname>
    <path>~\..\roms\zaccariapinball</path>
    <manufacturer>Pinball</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/zaccariapinball.svg](url)

**Pinball FX**
```
    <name>pinballfx</name>
    <fullname>Pinball FX</fullname>
    <path>~\..\roms\pinballfx</path>
    <manufacturer>Pinball</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/pinballfx.png](url)

**Pinball M**
```
    <name>pinballm</name>
    <fullname>Pinball M</fullname>
    <path>~\..\roms\pinballm</path>
    <manufacturer>Pinball</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/pinballm.png](url)

**Doom 3**
```
    <name>boom3</name>
    <fullname>Doom 3</fullname>
    <path>~\..\roms\boom3</path>
    <manufacturer>Ports</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/boom3-w.svg](url)

**Dinothawr**
```
    <name>dinothawr</name>
    <fullname>Dinothawr</fullname>
    <path>~\..\roms\dinothawr</path>
    <manufacturer>Ports</manufacturer>

```

**OpenLara**
```
    <name>openlara</name>
    <fullname>OpenLara</fullname>
    <path>~\..\roms\openlara</path>
    <manufacturer>Ports</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/openlara.svg](url)

**The Force Engine**
```
    <name>theforceengine</name>
    <fullname>The Force Engine</fullname>
    <path>~\..\roms\theforceengine</path>
    <manufacturer>Ports</manufacturer>
```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/theforceengine.png](url)

**Actionmax**
```
    <name>actionmax</name>
    <fullname>Actionmax</fullname>
    <path>~\..\roms\actionmax</path>
    <manufacturer>Worlds of Wonder</manufacturer>

```
[https://github.com/fabricecaruso/es-theme-carbon/blob/master/art/logos/actionmax.svg](url)

Thanks again for this great works !

**Comment by GeekRhapsody** [comment]
Missing System logos for the Modern Art Style added
