### ISSUE TITLE
Option to Use Marquee Images when Gamelist View Style is set to "Tiled"

### ISSUE THREAD

**Issue by CodeKonga** [GeekRhapsody/es-theme-tiled#10]
I think it would be really awesome if there was an option to use marquee images in the tiles when in "Tiled" gamelist view style. Having tiled marquee images would be both aesthetically pleasing and fairly intuitive to browse through as they are stylized versions of the game titles.

For an example of an ES-DE theme (which is unfortunately NOT on Batocera) that allows tiles to display Marquee images, see the texgriddy theme: https://steamdeckhq.com/wp-content/uploads/2023/03/TexGriddyTheme1.jpg

Thanks for making this awesome theme!

**Comment by GeekRhapsody** [comment]
Hi. Thanks for considering my theme. I've added a new gamelist view stlye: "Grid (Marquees)". Hope you like it
