### ISSUE TITLE
2 Minor Nitpicks - System Grid Icons and Battery/Time Cutoff

### ISSUE THREAD

**Issue by CodeKonga** [GeekRhapsody/es-theme-tiled#12]
Thanks so much for implementing the change I suggested with Marquee images in Tile mode so quickly. I am very grateful.

So I have two more minor nitpicks that I thought I would bring to your attention:

1) The clock and battery information gets cutoff on the right side of the screen. It doesn't matter if the time is set to 12-hour format or not or if the battery status is set to just the icon or the icon and text, it's always partially cutoff for me. If I disable the battery status indicator, then the network indicator is cutoff for me. I'm running your theme on the RG35XX H if that matters.

2) some of the system icons are off center (too high up), most noticeably for me, the N64 (especially when viewed in System Grid Size: 5x7). I just wish the icon was slightly lower in its box.

Thanks again for all your assistance and for making this awesome theme.

**Comment by GeekRhapsody** [comment]
1. I had not yet tested the theme in aspect ratios other than 16:9, but i plan to add support for at least 16:10 (steam deck) and 4:3 (RG35XX H and many others) in my next update.
2. The "Modern" art style option was not designed for grid sizes that do not result in square boxes, for size 5x7 i would recomment switch to the "Carbon" art style option. I'm also planning to add a "Just Logos" art style option in an update soon.

**Comment by GeekRhapsody** [comment]
Latest version of the theme now looks fine on 4:3 aspect ratios

**Comment by CodeKonga** [comment]
Thanks so much! Looks great.
