### ISSUE TITLE
Controller Battery Indicator is missing from the new version

### ISSUE THREAD

**Issue by jk7gr** [GeekRhapsody/es-theme-tiled#17]
I am great fan of your theme. In the latest version I have noticed a couple of issues
The main issues is related to the battery indication for the wireless controllers (left corner) that is missing completely. In the previous version this was working fine. I checked in the theme configuration but couldn't find something relevant.
The second (minor) is that when power saving is set to instant the CPU utilization in idle is up to 50% with no obvious reason. This again was behaving properly before. 
![image](https://github.com/user-attachments/assets/859cd3f3-651f-4c5a-a7e3-68d16ea80668)

I hope in the next version this will be rectified. 

Please let me know if you need more information. Thank you!

**Comment by GeekRhapsody** [comment]
I'm planning to adding back the controller indicator, and moving the clock/device battery/wifi indicator back to the top in a new version soon.

I'm not aware of any change that could be causing changes to the CPU utilization but will check. It would be helpful if you could tell what batocera/retrobat version you are using.

**Comment by jk7gr** [comment]
> I'm planning to adding back the controller indicator, and moving the clock/device battery/wifi indicator back to the top in a new version soon.
> 
> I'm not aware of any change that could be causing changes to the CPU utilization but will check. It would be helpful if you could tell what batocera/retrobat version you are using.

Thank you for the prompt response. I am currently using Batocera v.39 and I can help if there are things you would like to test.
